name: Github Actions Demo

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Ali ECS
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "13"

      - name: build project
        run: |
          npm install
          npm run build

      - name: SSH
        uses: fifsky/ssh-action@master
        with: 
          host: "120.27.0.225",
          pass: "Jiejing0427"
